import { Folder, Video } from "./types";

export const videos: Video[] = [
   {
      id: "1109-324",
      src: "/path/to/random/file1.mp4",
      title: "The Shawshank Redemption",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-325",
      src: "/path/to/random/file2.mp4",
      title: "The Godfather",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-326",
      src: "/path/to/random/file3.mp4",
      title: "The Dark Knight",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-327",
      src: "/path/to/random/file4.mp4",
      title: "Pulp Fiction",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-328",
      src: "/path/to/random/file5.mp4",
      title: "Forrest Gump",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-329",
      src: "/path/to/random/file6.mp4",
      title: "Inception",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-330",
      src: "/path/to/random/file7.mp4",
      title: "Fight Club",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-331",
      src: "/path/to/random/file8.mp4",
      title: "The Matrix",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-332",
      src: "/path/to/random/file9.mp4",
      title: "Goodfellas",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-333",
      src: "/path/to/random/file10.mp4",
      title: "Interstellar",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-334",
      src: "/path/to/random/file11.mp4",
      title: "Parasite",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-335",
      src: "/path/to/random/file12.mp4",
      title: "The Green Mile",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-336",
      src: "/path/to/random/file13.mp4",
      title: "Gladiator",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-337",
      src: "/path/to/random/file14.mp4",
      title: "Saving Private Ryan",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-338",
      src: "/path/to/random/file15.mp4",
      title: "Schindler's List",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-339",
      src: "/path/to/random/file16.mp4",
      title: "The Lion King",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-340",
      src: "/path/to/random/file17.mp4",
      title: "The Silence of the Lambs",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-341",
      src: "/path/to/random/file18.mp4",
      title: "Se7en",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-342",
      src: "/path/to/random/file19.mp4",
      title: "Django Unchained",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-343",
      src: "/path/to/random/file20.mp4",
      title: "The Departed",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-344",
      src: "/path/to/random/file21.mp4",
      title: "The Prestige",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-345",
      src: "/path/to/random/file22.mp4",
      title: "Whiplash",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-346",
      src: "/path/to/random/file23.mp4",
      title: "The Usual Suspects",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-347",
      src: "/path/to/random/file24.mp4",
      title: "Avengers: Endgame",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-348",
      src: "/path/to/random/file25.mp4",
      title: "Titanic",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-349",
      src: "/path/to/random/file26.mp4",
      title: "The Wolf of Wall Street",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-350",
      src: "/path/to/random/file27.mp4",
      title: "Logan",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-351",
      src: "/path/to/random/file28.mp4",
      title: "A Beautiful Mind",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-352",
      src: "/path/to/random/file29.mp4",
      title: "Joker",
      thumbnail: "/placeholderImage.png",
   },
   {
      id: "1109-353",
      src: "/path/to/random/file30.mp4",
      title: "Deadpool",
      thumbnail: "/placeholderImage.png",
   },
];

export const folders: Folder[] = [
   { id: "1", title: "Breaking Bad", src: "./Breaking_Bad" },
   { id: "2", title: "Game of Thrones", src: "./Game_of_Thrones" },
   { id: "3", title: "Stranger Things", src: "./Stranger_Things" },
   { id: "4", title: "The Office", src: "./The_Office" },
   { id: "5", title: "Sherlock", src: "./Sherlock" },
   { id: "6", title: "Westworld", src: "./Westworld" },
   { id: "7", title: "Friends", src: "./Friends" },
   { id: "8", title: "Better Call Saul", src: "./Better_Call_Saul" },
   { id: "9", title: "The Witcher", src: "./The_Witcher" },
   { id: "10", title: "House of the Dragon", src: "./House_of_the_Dragon" },
   { id: "11", title: "The Mandalorian", src: "./The_Mandalorian" },
   { id: "12", title: "Loki", src: "./Loki" },
   { id: "13", title: "The Boys", src: "./The_Boys" },
   { id: "14", title: "Squid Game", src: "./Squid_Game" },
   { id: "15", title: "Black Mirror", src: "./Black_Mirror" },
   { id: "16", title: "Money Heist", src: "./Money_Heist" },
   { id: "17", title: "Peaky Blinders", src: "./Peaky_Blinders" },
   { id: "18", title: "Dark", src: "./Dark" },
   { id: "19", title: "Mindhunter", src: "./Mindhunter" },
   { id: "20", title: "Narcos", src: "./Narcos" },
   { id: "21", title: "The Crown", src: "./The_Crown" },
   { id: "22", title: "True Detective", src: "./True_Detective" },
   { id: "23", title: "Dexter", src: "./Dexter" },
   { id: "24", title: "Rick and Morty", src: "./Rick_and_Morty" },
   { id: "25", title: "The Simpsons", src: "./The_Simpsons" },
   { id: "26", title: "Arcane", src: "./Arcane" },
   { id: "27", title: "Mr. Robot", src: "./Mr_Robot" },
   { id: "28", title: "Suits", src: "./Suits" },
   { id: "29", title: "Prison Break", src: "./Prison_Break" },
   { id: "30", title: "The Walking Dead", src: "./The_Walking_Dead" },
   { id: "31", title: "Chernobyl", src: "./Chernobyl" },
   { id: "32", title: "How I Met Your Mother", src: "./How_I_Met_Your_Mother" },
   { id: "33", title: "Brooklyn Nine-Nine", src: "./Brooklyn_Nine_Nine" },
   { id: "34", title: "Fargo", src: "./Fargo" },
   { id: "35", title: "Lost", src: "./Lost" },
];
